name: Test on all branches and merge Dependabot Pull Requests when tests are succesfull

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dump GitHub context
      env:
        GITHUB_ACTOR: ${{ toJson(github.actor) }}
        GITHUB_EVENT_NAME: ${{ toJson(github.event_name) }}
      run: echo "GITHUB_ACTOR <$GITHUB_ACTOR>, GITHUB_EVENT_NAME <GITHUB_EVENT_NAME>"
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B test --file pom.xml
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: archive test results
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true
    - name: merge dependabot pull request
      if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: 1
        method: merge # squash merge rebase
        repo: juliangruber/octokit-action

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
