name: test and if successful, merge dependabot pull requests
on:
  push:
  pull_request_target:

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  print-context:
    name: Print Context
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Actor
        run: echo "The job was automatically triggered by actor ${{ github.actor }}."

  test:
    name: Build and Test with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: mvn -B test --file pom.xml
      - name: Upload Test Results as Artefact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: '**/target/surefire-reports/*.xml'
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          artifact: test-results
          name: Maven Test Results
          path: '**/*.xml'
          reporter: java-junit
          fail-on-error: true

  merge_dependabot_pull_requests:
    if: github.actor == 'dependabot[bot]'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Enable auto-merge for Dependabot PRs
      if: contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Approve a PR
      run: gh pr review --approve "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
